// GENERATED by scripts authoring pass from design/design.json.
// Hand-crafted tile grids + placements for the four v1 areas.
import type { AreaDef } from "../shared/area";

export const AREAS: Record<string, AreaDef> = {
  "hearthglow": {
    "id": "hearthglow",
    "name": "Hearthglow Village",
    "biome": "cozy-hamlet",
    "palette": {
      "ground1": "#8FD97C",
      "ground2": "#7CC968",
      "accent": "#FFB55C",
      "fog": "#AECBE8"
    },
    "tiles": [
      "##############pp##############",
      "#............fppf............#",
      "#.............pp.............#",
      "#..##.........pp........##...#",
      "#..##.........pp........##...#",
      "#.............pp.............#",
      "#.......f.....pp.....f.......#",
      "#.............pp.............#",
      "#...........pppppp...........#",
      "#..##.......pppppp......##...#",
      "#..##.......pp##pp......##...#",
      "#...........pppppp...........#",
      "#...........pppppp...........#",
      "#.......f............f.......#",
      "#............................#",
      "#..##......##....##.....##...#",
      "#..##......##....##.....##...#",
      "#.....f................f.....#",
      "#............................#",
      "##############################"
    ],
    "spawn": {
      "x": 15,
      "z": 12
    },
    "props": [
      {
        "kind": "house",
        "x": 3.5,
        "z": 3.5
      },
      {
        "kind": "house",
        "x": 24.5,
        "z": 3.5
      },
      {
        "kind": "house",
        "x": 3.5,
        "z": 9.5
      },
      {
        "kind": "house",
        "x": 24.5,
        "z": 9.5
      },
      {
        "kind": "house",
        "x": 3.5,
        "z": 15.5
      },
      {
        "kind": "house",
        "x": 24.5,
        "z": 15.5
      },
      {
        "kind": "house",
        "x": 11.5,
        "z": 15.5
      },
      {
        "kind": "house",
        "x": 17.5,
        "z": 15.5
      },
      {
        "kind": "lantern",
        "x": 14.5,
        "z": 10,
        "scale": 1.6,
        "tint": "#FFB55C"
      },
      {
        "kind": "lantern",
        "x": 12,
        "z": 8
      },
      {
        "kind": "lantern",
        "x": 17,
        "z": 8
      },
      {
        "kind": "lantern",
        "x": 12,
        "z": 12
      },
      {
        "kind": "lantern",
        "x": 17,
        "z": 12
      },
      {
        "kind": "arch",
        "x": 14.5,
        "z": 1,
        "tint": "#FF9EC4"
      },
      {
        "kind": "tree",
        "x": 8,
        "z": 4
      },
      {
        "kind": "tree",
        "x": 21,
        "z": 4
      },
      {
        "kind": "tree",
        "x": 8,
        "z": 17
      },
      {
        "kind": "tree",
        "x": 21,
        "z": 17
      },
      {
        "kind": "rock",
        "x": 9,
        "z": 10
      },
      {
        "kind": "stump",
        "x": 20,
        "z": 13
      },
      {
        "kind": "fence",
        "x": 10,
        "z": 17
      },
      {
        "kind": "fence",
        "x": 19,
        "z": 3
      }
    ],
    "npcs": [
      {
        "id": "npc-archivist-maru",
        "name": "Archivist Maru",
        "role": "codex-giver",
        "x": 13,
        "z": 10,
        "hue": 45,
        "dialogue": [
          "This Codex is older than the village, older than me, and it still boots up faster than my kettle.",
          "Syncing isn't taking, dear. It's an agreement — the glyph only holds if a Gaiamon is too tired to argue and a little curious about you.",
          "If the screen ever fogs up, that isn't broken. Something ancient nearby is dreaming. Probably fine."
        ]
      },
      {
        "id": "npc-posy",
        "name": "Posy",
        "role": "innkeeper-healer",
        "x": 6,
        "z": 10,
        "hue": 330,
        "dialogue": [
          "Rest your team here whenever you like — my stew mends HP in real life and, I'm told, emotionally.",
          "A Warden Synced a Gaiamon in my kitchen once. Scorched a perfect circle in the floor. I charge extra for that now."
        ]
      },
      {
        "id": "npc-nib",
        "name": "Nib",
        "role": "codex-obsessed-kid",
        "x": 17,
        "z": 6,
        "hue": 205,
        "dialogue": [
          "When I get MY Codex I'm gonna Sync a hundred Gaiamon. Maybe the hearth itself. Can you Sync a fire? Write that down.",
          "Archivist Maru says the Codex chooses its Warden. Mine is choosing very, very slowly.",
          "The meadow's north! Wild ones hide in the tall grass 'cause they think it's funny when you jump."
        ]
      }
    ],
    "exits": [
      {
        "x": 14,
        "z": 0,
        "toArea": "petalway-meadow",
        "toX": 14,
        "toZ": 19,
        "label": "North — Petalway Meadow"
      },
      {
        "x": 15,
        "z": 0,
        "toArea": "petalway-meadow",
        "toX": 14,
        "toZ": 19,
        "label": "North — Petalway Meadow"
      }
    ],
    "encounters": [],
    "triggers": [
      {
        "kind": "heal",
        "x": 8,
        "z": 12,
        "id": "hearthglow-inn",
        "text": "Rest your team at Posy's hearth. Your Gaiamon are fully restored."
      },
      {
        "kind": "sign",
        "x": 16,
        "z": 2,
        "id": "hearthglow-sign-north",
        "text": "↑ Petalway Meadow. Mind the tall grass — the wild ones bite (affectionately)."
      },
      {
        "kind": "sign",
        "x": 12,
        "z": 7,
        "id": "hearthglow-sign-hearth",
        "text": "The hearth has burned since before the village. Please don't poke it. — Posy"
      }
    ],
    "encounterRate": 0
  },
  "petalway-meadow": {
    "id": "petalway-meadow",
    "name": "Petalway Meadow",
    "biome": "sunny-meadow",
    "palette": {
      "ground1": "#96E072",
      "ground2": "#85D162",
      "accent": "#FF9EC4",
      "fog": "#B7D8EE"
    },
    "tiles": [
      "#############pp#############",
      "#ggggggggggggppgggggggggggg#",
      "#ggggggggggggppgggggggggggg#",
      "#ggggppppppppppgggggggggggg#",
      "#ggggppppppppppgggggggggfgg#",
      "#ggg#ppgggggggggggggggg#ggg#",
      "#ggggppggfggggggggggggggggg#",
      "#ggggppgggg#ggggg#ggggggggg#",
      "#ggggppgggggggggggggggggggg#",
      "#ggggppppppppppppppppppgggg#",
      "#ggfgppppppppppppppppppgggg#",
      "#ggggggggggggggggggggppg#gg#",
      "#gggggggg#ggggg##gffgppgggg#",
      "#ggggggggggggggggggggppgggg#",
      "#ggggggggggggggggggggppgggg#",
      "#ggggggggggggppppppppppgggg#",
      "#ggggggggggggppppppppppgggg#",
      "#gggggg#gggggppgggggggggggg#",
      "#ggg#gggggffgppgggg#ggggggg#",
      "#ggggggggggggppgfgggggggggg#",
      "#ggggggggggggppgggggggggggg#",
      "#############pp#############"
    ],
    "spawn": {
      "x": 13,
      "z": 19
    },
    "props": [
      {
        "kind": "tree",
        "x": 4,
        "z": 5,
        "tint": "#FF9EC4"
      },
      {
        "kind": "tree",
        "x": 23,
        "z": 5,
        "tint": "#FF9EC4"
      },
      {
        "kind": "tree",
        "x": 9,
        "z": 12
      },
      {
        "kind": "tree",
        "x": 19,
        "z": 18
      },
      {
        "kind": "tree",
        "x": 24,
        "z": 11
      },
      {
        "kind": "tree",
        "x": 4,
        "z": 18
      },
      {
        "kind": "rock",
        "x": 11,
        "z": 7
      },
      {
        "kind": "rock",
        "x": 17,
        "z": 7
      },
      {
        "kind": "rock",
        "x": 7,
        "z": 17
      },
      {
        "kind": "fence",
        "x": 15,
        "z": 12
      },
      {
        "kind": "fence",
        "x": 16,
        "z": 12
      },
      {
        "kind": "bush",
        "x": 10,
        "z": 18
      },
      {
        "kind": "bush",
        "x": 18,
        "z": 12
      },
      {
        "kind": "bush",
        "x": 9,
        "z": 6
      }
    ],
    "npcs": [
      {
        "id": "npc-shepherd-fenn",
        "name": "Fenn",
        "role": "napping-shepherd",
        "x": 8,
        "z": 14,
        "hue": 100,
        "dialogue": [
          "Zzz — huh? Oh. I wasn't sleeping, I was calibrating. The grass naps back, you know.",
          "Weaken 'em gently before you Sync. A scared Gaiamon wriggles right off the glyph — then you feel bad and it feels smug."
        ]
      },
      {
        "id": "npc-waykeeper-lyra",
        "name": "Waykeeper Lyra",
        "role": "novice-rival",
        "x": 20,
        "z": 10,
        "hue": 285,
        "dialogue": [
          "My Codex says my sync rate is 'statistically optimistic.' I choose to take that as a compliment.",
          "Race you to the caverns! Well — after this. Well — after my team stops hiding in the grass.",
          "The trick is status. A drowsy Gaiamon practically Syncs itself. A grumpy one? Good luck."
        ]
      },
      {
        "id": "npc-botanist-wren",
        "name": "Wren",
        "role": "field-botanist",
        "x": 17,
        "z": 6,
        "hue": 150,
        "dialogue": [
          "This seed-fluff never lands. Never! I watched one piece for three days. My Codex logged it as 'probably Fable nonsense.'",
          "Tall grass grows tall because wild Gaiamon fertilize it with mischief. That's not science. But it's not NOT science."
        ]
      }
    ],
    "exits": [
      {
        "x": 13,
        "z": 21,
        "toArea": "hearthglow",
        "toX": 15,
        "toZ": 2,
        "label": "South — Hearthglow"
      },
      {
        "x": 14,
        "z": 21,
        "toArea": "hearthglow",
        "toX": 15,
        "toZ": 2,
        "label": "South — Hearthglow"
      },
      {
        "x": 13,
        "z": 0,
        "toArea": "gloam-caverns",
        "toX": 14,
        "toZ": 19,
        "label": "North — Gloamlight Caverns"
      },
      {
        "x": 14,
        "z": 0,
        "toArea": "gloam-caverns",
        "toX": 14,
        "toZ": 19,
        "label": "North — Gloamlight Caverns"
      }
    ],
    "encounters": [
      {
        "speciesId": "dandelamb",
        "weight": 45,
        "minLevel": 2,
        "maxLevel": 3
      },
      {
        "speciesId": "pottle",
        "weight": 35,
        "minLevel": 2,
        "maxLevel": 4
      },
      {
        "speciesId": "zizzle",
        "weight": 20,
        "minLevel": 3,
        "maxLevel": 4
      }
    ],
    "triggers": [
      {
        "kind": "sign",
        "x": 11,
        "z": 20,
        "id": "petalway-sign-south",
        "text": "Petalway Meadow. Step lightly — shy Gaiamon nap in the tall grass."
      },
      {
        "kind": "sign",
        "x": 17,
        "z": 3,
        "id": "petalway-sign-north",
        "text": "Cool air ahead. The Gloamlight Caverns glow just north."
      }
    ],
    "encounterRate": 9
  },
  "gloam-caverns": {
    "id": "gloam-caverns",
    "name": "Gloamlight Caverns",
    "biome": "glowing-cave",
    "palette": {
      "ground1": "#4A4E7C",
      "ground2": "#3E4169",
      "accent": "#6CF0D2",
      "fog": "#2D3250"
    },
    "tiles": [
      "##############pp##############",
      "#############....#############",
      "#####............#############",
      "#####.gg.........#############",
      "#####............#############",
      "#####....#####################",
      "#####.....................####",
      "#####.....ggg.............####",
      "#####.....................####",
      "######################....####",
      "######################..g.####",
      "######################..g.####",
      "######################....####",
      "######################....####",
      "#############.............####",
      "#############.....ggg.....####",
      "#############.............####",
      "#############....#############",
      "#############.gg.#############",
      "#############....#############",
      "#############....#############",
      "##############pp##############"
    ],
    "spawn": {
      "x": 14,
      "z": 19
    },
    "props": [
      {
        "kind": "crystal",
        "x": 12,
        "z": 16,
        "tint": "#6CF0D2"
      },
      {
        "kind": "crystal",
        "x": 17,
        "z": 13,
        "tint": "#6CF0D2"
      },
      {
        "kind": "crystal",
        "x": 26,
        "z": 11,
        "tint": "#6CF0D2"
      },
      {
        "kind": "crystal",
        "x": 4,
        "z": 7,
        "tint": "#6CF0D2"
      },
      {
        "kind": "crystal",
        "x": 9,
        "z": 3,
        "tint": "#6CF0D2"
      },
      {
        "kind": "crystal",
        "x": 16,
        "z": 5,
        "tint": "#6CF0D2"
      },
      {
        "kind": "lantern",
        "x": 15,
        "z": 20
      },
      {
        "kind": "lantern",
        "x": 23,
        "z": 13
      },
      {
        "kind": "lantern",
        "x": 6,
        "z": 7
      },
      {
        "kind": "lantern",
        "x": 14,
        "z": 3
      },
      {
        "kind": "bush",
        "x": 18,
        "z": 15,
        "tint": "#6CF0D2"
      },
      {
        "kind": "bush",
        "x": 11,
        "z": 7,
        "tint": "#6CF0D2"
      },
      {
        "kind": "bush",
        "x": 6,
        "z": 3,
        "tint": "#6CF0D2"
      },
      {
        "kind": "rock",
        "x": 12,
        "z": 13
      },
      {
        "kind": "rock",
        "x": 26,
        "z": 9
      },
      {
        "kind": "rock",
        "x": 5,
        "z": 5
      }
    ],
    "npcs": [
      {
        "id": "npc-mycologist-oona",
        "name": "Oona",
        "role": "mushroom-farmer",
        "x": 15,
        "z": 17,
        "hue": 165,
        "dialogue": [
          "The moss glows brighter for kind people. You're practically a lantern. I'm only a little jealous.",
          "Don't Sync anything standing in my crop, please. The last glyph flash-fried a whole harvest into very pretty charcoal."
        ]
      },
      {
        "id": "npc-mothkeeper-silas",
        "name": "Silas",
        "role": "glow-moth-enthusiast",
        "x": 23,
        "z": 10,
        "hue": 260,
        "dialogue": [
          "Shh. Listen — when the moths land on the crystals, they chime. My Codex has forty hours of it. Want to hear all of them?",
          "Umbral ones down here aren't scary. They're shy. There's a difference, and it lives mostly in the eyebrows.",
          "Everyone rushes to the Waystone. It has waited nine hundred years. It can wait for you to look at a moth."
        ]
      },
      {
        "id": "npc-lost-tourist-perl",
        "name": "Perl",
        "role": "cheerfully-lost-tourist",
        "x": 7,
        "z": 3,
        "hue": 35,
        "dialogue": [
          "Am I lost? Officially, yes. Spiritually, I have never been more found.",
          "My Codex map just shows a mushroom doodle where I'm standing. I think it's being affectionate."
        ]
      }
    ],
    "exits": [
      {
        "x": 14,
        "z": 21,
        "toArea": "petalway-meadow",
        "toX": 13,
        "toZ": 2,
        "label": "South — Petalway Meadow"
      },
      {
        "x": 15,
        "z": 21,
        "toArea": "petalway-meadow",
        "toX": 13,
        "toZ": 2,
        "label": "South — Petalway Meadow"
      },
      {
        "x": 14,
        "z": 0,
        "toArea": "waystone-rise",
        "toX": 13,
        "toZ": 21,
        "label": "North — Waystone Rise"
      },
      {
        "x": 15,
        "z": 0,
        "toArea": "waystone-rise",
        "toX": 13,
        "toZ": 21,
        "label": "North — Waystone Rise"
      }
    ],
    "encounters": [
      {
        "speciesId": "nibbin",
        "weight": 40,
        "minLevel": 5,
        "maxLevel": 7
      },
      {
        "speciesId": "pottle",
        "weight": 35,
        "minLevel": 5,
        "maxLevel": 8
      },
      {
        "speciesId": "zizzle",
        "weight": 20,
        "minLevel": 6,
        "maxLevel": 8
      },
      {
        "speciesId": "tattertale",
        "weight": 5,
        "minLevel": 7,
        "maxLevel": 8
      }
    ],
    "triggers": [
      {
        "kind": "sign",
        "x": 15,
        "z": 19,
        "id": "gloam-sign-south",
        "text": "Gloamlight Caverns. The moss lights your way — if you're kind to it."
      },
      {
        "kind": "sign",
        "x": 14,
        "z": 2,
        "id": "gloam-sign-north",
        "text": "↑ Waystone Rise. Watch your footing — and your echoes."
      }
    ],
    "encounterRate": 8
  },
  "waystone-rise": {
    "id": "waystone-rise",
    "name": "Waystone Rise",
    "biome": "ancient-highland-ruin",
    "palette": {
      "ground1": "#B0A8C9",
      "ground2": "#9E96B8",
      "accent": "#FFD86B",
      "fog": "#E7C27A"
    },
    "tiles": [
      "############################",
      "#############p##############",
      "##########ppppppp###########",
      "#########ppppppppp##########",
      "#########ppppppppp##########",
      "#########ppppppppp##########",
      "########ppppppppppp#########",
      "#########ppppppppp##########",
      "#########ppppppppp##########",
      "#########ppppppppp##########",
      "##########ppppppp###########",
      "############ppp#############",
      "###.........ppp..........###",
      "###..........pp..........###",
      "###...g......pp.....g....###",
      "###..........pp..........###",
      "###..........pp..........###",
      "###..........pp..........###",
      "###...gg.....pp.....gg...###",
      "###..........pp..........###",
      "###.......g..pp..g.......###",
      "###..........pp..........###",
      "###..........pp..........###",
      "#############pp#############"
    ],
    "spawn": {
      "x": 13,
      "z": 21
    },
    "props": [
      {
        "kind": "waystone",
        "x": 13,
        "z": 9,
        "scale": 1.8,
        "tint": "#FFD86B"
      },
      {
        "kind": "arch",
        "x": 13,
        "z": 11,
        "tint": "#FFD86B"
      },
      {
        "kind": "lantern",
        "x": 9,
        "z": 3,
        "tint": "#FFD86B"
      },
      {
        "kind": "lantern",
        "x": 17,
        "z": 3,
        "tint": "#FFD86B"
      },
      {
        "kind": "lantern",
        "x": 8,
        "z": 7,
        "tint": "#FFD86B"
      },
      {
        "kind": "lantern",
        "x": 18,
        "z": 7,
        "tint": "#FFD86B"
      },
      {
        "kind": "lantern",
        "x": 10,
        "z": 11,
        "tint": "#FFD86B"
      },
      {
        "kind": "lantern",
        "x": 16,
        "z": 11,
        "tint": "#FFD86B"
      },
      {
        "kind": "rock",
        "x": 7,
        "z": 14
      },
      {
        "kind": "rock",
        "x": 20,
        "z": 13
      },
      {
        "kind": "rock",
        "x": 6,
        "z": 21
      },
      {
        "kind": "rock",
        "x": 21,
        "z": 21
      },
      {
        "kind": "rock",
        "x": 18,
        "z": 18,
        "scale": 1.4
      },
      {
        "kind": "rock",
        "x": 9,
        "z": 17,
        "scale": 1.4
      },
      {
        "kind": "bush",
        "x": 6,
        "z": 18
      },
      {
        "kind": "bush",
        "x": 20,
        "z": 18
      },
      {
        "kind": "bush",
        "x": 10,
        "z": 20
      },
      {
        "kind": "stump",
        "x": 11,
        "z": 13
      },
      {
        "kind": "stump",
        "x": 15,
        "z": 13
      }
    ],
    "npcs": [
      {
        "id": "npc-keeper-solenne",
        "name": "Keeper Solenne",
        "role": "sanctum-keeper",
        "x": 13,
        "z": 15,
        "hue": 190,
        "dialogue": [
          "Oh! A visitor — shh, one second, the reeds are mid-sentence... okay. Hello! You brought a singing slab. May I battle it? I mean you. May I battle you?",
          "The Trial isn't about strength. It's whether your team trusts you when the wind howls. Also, a little, strength.",
          "Don't try to Sync the Titan. The glyph would need to be the size of the plateau — and honestly, Cairnoss would find it rude."
        ],
        "battle": {
          "kind": "trainer",
          "id": "keeper-solenne"
        }
      },
      {
        "id": "npc-mason-edda",
        "name": "Edda",
        "role": "ruin-historian",
        "x": 8,
        "z": 18,
        "hue": 30,
        "dialogue": [
          "These glyphs predate the Codex — or the Codex predates them. History up here is less a line, more a polite shrug.",
          "Every cracked tile matches a Titan footstep. I've numbered them. Tile 214 is my favorite. It has ambition."
        ]
      },
      {
        "id": "npc-lookout-tam",
        "name": "Tam",
        "role": "nervous-lookout",
        "x": 20,
        "z": 16,
        "hue": 55,
        "dialogue": [
          "If the ground purrs, walk calmly to the arch. If the ground HUMS, run calmly to the arch.",
          "My Codex has one alert set: 'TITAN AWAKE.' It's never gone off. Today feels like a great day for it to keep not going off."
        ]
      }
    ],
    "exits": [
      {
        "x": 13,
        "z": 23,
        "toArea": "gloam-caverns",
        "toX": 14,
        "toZ": 2,
        "label": "South — Gloamlight Caverns"
      },
      {
        "x": 14,
        "z": 23,
        "toArea": "gloam-caverns",
        "toX": 14,
        "toZ": 2,
        "label": "South — Gloamlight Caverns"
      }
    ],
    "encounters": [
      {
        "speciesId": "thistleram",
        "weight": 55,
        "minLevel": 10,
        "maxLevel": 12
      },
      {
        "speciesId": "nibbin",
        "weight": 35,
        "minLevel": 9,
        "maxLevel": 11
      },
      {
        "speciesId": "tattertale",
        "weight": 10,
        "minLevel": 11,
        "maxLevel": 12
      }
    ],
    "triggers": [
      {
        "kind": "sign",
        "x": 13,
        "z": 20,
        "id": "waystone-sign",
        "text": "Waystone Rise. Clear the Trial of Echoes to wake what sleeps beneath."
      },
      {
        "kind": "trial",
        "x": 13,
        "z": 10,
        "id": "waystone-trial",
        "text": "The Waystone hums, its glyphs brightening rung by rung. Face the Trial of Echoes?"
      },
      {
        "kind": "titan",
        "x": 13,
        "z": 4,
        "id": "titan-cairnoss",
        "text": "The plateau itself draws a slow breath. Moss stirs on ancient stone — the Sleeper wakes."
      }
    ],
    "encounterRate": 8
  }
};

export const START_AREA = "hearthglow";
